/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm")
}

kotlinProject()


dependencies {
    implementation( "io.javalin:javalin:3.11.0")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.10.3")
    implementation("org.slf4j:slf4j-simple:1.7.30")

}
