/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm")
}

kotlinProject()
dataLibs()
dependencies {
    implementation(project(":Application-data"))
    implementation(project(":Application-models"))
}