/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
    kotlin("jvm")
}

kotlinProject()
dataLibs()

application {
    // Define the main class for the application.
    mainClass.set("com.gruzini.app.AppKt")
}

dependencies {

    implementation(project(":Application-rest"))
    implementation(project(":Application-data"))
}
